/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesCategoryRouteImport } from './routes/services.$category'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardProviderIndexRouteImport } from './routes/dashboard/provider.index'
import { Route as DashboardClientIndexRouteImport } from './routes/dashboard/client.index'
import { Route as DashboardProviderServicesRouteImport } from './routes/dashboard/provider.services'
import { Route as DashboardProviderProjectsRouteImport } from './routes/dashboard/provider.projects'
import { Route as DashboardProviderPortfolioRouteImport } from './routes/dashboard/provider.portfolio'
import { Route as DashboardProviderKycRouteImport } from './routes/dashboard/provider.kyc'
import { Route as DashboardClientProjectsIndexRouteImport } from './routes/dashboard/client.projects.index'
import { Route as DashboardClientProjectsNewRouteImport } from './routes/dashboard/client.projects.new'
import { Route as DashboardClientProjectsIdRouteImport } from './routes/dashboard/client.projects.$id'
import { Route as ApiPublicFapshiWebhookRouteImport } from './routes/api/public/fapshi/webhook'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCategoryRoute = ServicesCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ServicesRoute,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProviderIndexRoute = DashboardProviderIndexRouteImport.update({
  id: '/dashboard/provider/',
  path: '/dashboard/provider/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClientIndexRoute = DashboardClientIndexRouteImport.update({
  id: '/dashboard/client/',
  path: '/dashboard/client/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProviderServicesRoute =
  DashboardProviderServicesRouteImport.update({
    id: '/dashboard/provider/services',
    path: '/dashboard/provider/services',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardProviderProjectsRoute =
  DashboardProviderProjectsRouteImport.update({
    id: '/dashboard/provider/projects',
    path: '/dashboard/provider/projects',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardProviderPortfolioRoute =
  DashboardProviderPortfolioRouteImport.update({
    id: '/dashboard/provider/portfolio',
    path: '/dashboard/provider/portfolio',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardProviderKycRoute = DashboardProviderKycRouteImport.update({
  id: '/dashboard/provider/kyc',
  path: '/dashboard/provider/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClientProjectsIndexRoute =
  DashboardClientProjectsIndexRouteImport.update({
    id: '/dashboard/client/projects/',
    path: '/dashboard/client/projects/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClientProjectsNewRoute =
  DashboardClientProjectsNewRouteImport.update({
    id: '/dashboard/client/projects/new',
    path: '/dashboard/client/projects/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardClientProjectsIdRoute =
  DashboardClientProjectsIdRouteImport.update({
    id: '/dashboard/client/projects/$id',
    path: '/dashboard/client/projects/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFapshiWebhookRoute = ApiPublicFapshiWebhookRouteImport.update({
  id: '/api/public/fapshi/webhook',
  path: '/api/public/fapshi/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/services/$category': typeof ServicesCategoryRoute
  '/services/': typeof ServicesIndexRoute
  '/dashboard/provider/kyc': typeof DashboardProviderKycRoute
  '/dashboard/provider/portfolio': typeof DashboardProviderPortfolioRoute
  '/dashboard/provider/projects': typeof DashboardProviderProjectsRoute
  '/dashboard/provider/services': typeof DashboardProviderServicesRoute
  '/dashboard/client/': typeof DashboardClientIndexRoute
  '/dashboard/provider/': typeof DashboardProviderIndexRoute
  '/api/public/fapshi/webhook': typeof ApiPublicFapshiWebhookRoute
  '/dashboard/client/projects/$id': typeof DashboardClientProjectsIdRoute
  '/dashboard/client/projects/new': typeof DashboardClientProjectsNewRoute
  '/dashboard/client/projects/': typeof DashboardClientProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/services/$category': typeof ServicesCategoryRoute
  '/services': typeof ServicesIndexRoute
  '/dashboard/provider/kyc': typeof DashboardProviderKycRoute
  '/dashboard/provider/portfolio': typeof DashboardProviderPortfolioRoute
  '/dashboard/provider/projects': typeof DashboardProviderProjectsRoute
  '/dashboard/provider/services': typeof DashboardProviderServicesRoute
  '/dashboard/client': typeof DashboardClientIndexRoute
  '/dashboard/provider': typeof DashboardProviderIndexRoute
  '/api/public/fapshi/webhook': typeof ApiPublicFapshiWebhookRoute
  '/dashboard/client/projects/$id': typeof DashboardClientProjectsIdRoute
  '/dashboard/client/projects/new': typeof DashboardClientProjectsNewRoute
  '/dashboard/client/projects': typeof DashboardClientProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/services/$category': typeof ServicesCategoryRoute
  '/services/': typeof ServicesIndexRoute
  '/dashboard/provider/kyc': typeof DashboardProviderKycRoute
  '/dashboard/provider/portfolio': typeof DashboardProviderPortfolioRoute
  '/dashboard/provider/projects': typeof DashboardProviderProjectsRoute
  '/dashboard/provider/services': typeof DashboardProviderServicesRoute
  '/dashboard/client/': typeof DashboardClientIndexRoute
  '/dashboard/provider/': typeof DashboardProviderIndexRoute
  '/api/public/fapshi/webhook': typeof ApiPublicFapshiWebhookRoute
  '/dashboard/client/projects/$id': typeof DashboardClientProjectsIdRoute
  '/dashboard/client/projects/new': typeof DashboardClientProjectsNewRoute
  '/dashboard/client/projects/': typeof DashboardClientProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cgu'
    | '/confidentialite'
    | '/contact'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/services'
    | '/dashboard/admin'
    | '/providers/$id'
    | '/services/$category'
    | '/services/'
    | '/dashboard/provider/kyc'
    | '/dashboard/provider/portfolio'
    | '/dashboard/provider/projects'
    | '/dashboard/provider/services'
    | '/dashboard/client/'
    | '/dashboard/provider/'
    | '/api/public/fapshi/webhook'
    | '/dashboard/client/projects/$id'
    | '/dashboard/client/projects/new'
    | '/dashboard/client/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgu'
    | '/confidentialite'
    | '/contact'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/dashboard/admin'
    | '/providers/$id'
    | '/services/$category'
    | '/services'
    | '/dashboard/provider/kyc'
    | '/dashboard/provider/portfolio'
    | '/dashboard/provider/projects'
    | '/dashboard/provider/services'
    | '/dashboard/client'
    | '/dashboard/provider'
    | '/api/public/fapshi/webhook'
    | '/dashboard/client/projects/$id'
    | '/dashboard/client/projects/new'
    | '/dashboard/client/projects'
  id:
    | '__root__'
    | '/'
    | '/cgu'
    | '/confidentialite'
    | '/contact'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/services'
    | '/dashboard/admin'
    | '/providers/$id'
    | '/services/$category'
    | '/services/'
    | '/dashboard/provider/kyc'
    | '/dashboard/provider/portfolio'
    | '/dashboard/provider/projects'
    | '/dashboard/provider/services'
    | '/dashboard/client/'
    | '/dashboard/provider/'
    | '/api/public/fapshi/webhook'
    | '/dashboard/client/projects/$id'
    | '/dashboard/client/projects/new'
    | '/dashboard/client/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CguRoute: typeof CguRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  DashboardAdminRoute: typeof DashboardAdminRoute
  ProvidersIdRoute: typeof ProvidersIdRoute
  DashboardProviderKycRoute: typeof DashboardProviderKycRoute
  DashboardProviderPortfolioRoute: typeof DashboardProviderPortfolioRoute
  DashboardProviderProjectsRoute: typeof DashboardProviderProjectsRoute
  DashboardProviderServicesRoute: typeof DashboardProviderServicesRoute
  DashboardClientIndexRoute: typeof DashboardClientIndexRoute
  DashboardProviderIndexRoute: typeof DashboardProviderIndexRoute
  ApiPublicFapshiWebhookRoute: typeof ApiPublicFapshiWebhookRoute
  DashboardClientProjectsIdRoute: typeof DashboardClientProjectsIdRoute
  DashboardClientProjectsNewRoute: typeof DashboardClientProjectsNewRoute
  DashboardClientProjectsIndexRoute: typeof DashboardClientProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$category': {
      id: '/services/$category'
      path: '/$category'
      fullPath: '/services/$category'
      preLoaderRoute: typeof ServicesCategoryRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/provider/': {
      id: '/dashboard/provider/'
      path: '/dashboard/provider'
      fullPath: '/dashboard/provider/'
      preLoaderRoute: typeof DashboardProviderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/client/': {
      id: '/dashboard/client/'
      path: '/dashboard/client'
      fullPath: '/dashboard/client/'
      preLoaderRoute: typeof DashboardClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/provider/services': {
      id: '/dashboard/provider/services'
      path: '/dashboard/provider/services'
      fullPath: '/dashboard/provider/services'
      preLoaderRoute: typeof DashboardProviderServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/provider/projects': {
      id: '/dashboard/provider/projects'
      path: '/dashboard/provider/projects'
      fullPath: '/dashboard/provider/projects'
      preLoaderRoute: typeof DashboardProviderProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/provider/portfolio': {
      id: '/dashboard/provider/portfolio'
      path: '/dashboard/provider/portfolio'
      fullPath: '/dashboard/provider/portfolio'
      preLoaderRoute: typeof DashboardProviderPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/provider/kyc': {
      id: '/dashboard/provider/kyc'
      path: '/dashboard/provider/kyc'
      fullPath: '/dashboard/provider/kyc'
      preLoaderRoute: typeof DashboardProviderKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/client/projects/': {
      id: '/dashboard/client/projects/'
      path: '/dashboard/client/projects'
      fullPath: '/dashboard/client/projects/'
      preLoaderRoute: typeof DashboardClientProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/client/projects/new': {
      id: '/dashboard/client/projects/new'
      path: '/dashboard/client/projects/new'
      fullPath: '/dashboard/client/projects/new'
      preLoaderRoute: typeof DashboardClientProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/client/projects/$id': {
      id: '/dashboard/client/projects/$id'
      path: '/dashboard/client/projects/$id'
      fullPath: '/dashboard/client/projects/$id'
      preLoaderRoute: typeof DashboardClientProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fapshi/webhook': {
      id: '/api/public/fapshi/webhook'
      path: '/api/public/fapshi/webhook'
      fullPath: '/api/public/fapshi/webhook'
      preLoaderRoute: typeof ApiPublicFapshiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesCategoryRoute: typeof ServicesCategoryRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCategoryRoute: ServicesCategoryRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CguRoute: CguRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRouteWithChildren,
  DashboardAdminRoute: DashboardAdminRoute,
  ProvidersIdRoute: ProvidersIdRoute,
  DashboardProviderKycRoute: DashboardProviderKycRoute,
  DashboardProviderPortfolioRoute: DashboardProviderPortfolioRoute,
  DashboardProviderProjectsRoute: DashboardProviderProjectsRoute,
  DashboardProviderServicesRoute: DashboardProviderServicesRoute,
  DashboardClientIndexRoute: DashboardClientIndexRoute,
  DashboardProviderIndexRoute: DashboardProviderIndexRoute,
  ApiPublicFapshiWebhookRoute: ApiPublicFapshiWebhookRoute,
  DashboardClientProjectsIdRoute: DashboardClientProjectsIdRoute,
  DashboardClientProjectsNewRoute: DashboardClientProjectsNewRoute,
  DashboardClientProjectsIndexRoute: DashboardClientProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
